### ISSUE TITLE
Project is not working correctly in pipelines...

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#148]
This fails to compile.  Changing `project` to `group_by` works.

```
      query: table('malloytest.aircraft')->{
        aggregate: f is count(*)
      }->{
        project: f2 is f+1
      }
```

This also fails.  Might be the same thing.  Changing 'project' to 'group_by' allows these to compile.

```
      query: table('malloytest.airports')->{
        aggregate: airport_count is count()
        nest: pipe_turtle is {
          group_by: [
            state
            county
          ]
          aggregate: a is count()
        } -> {
          project: [
            state is upper(state)
            a
          ]
        } -> {
          group_by: state
          aggregate: total_airports is a.sum()
        }
      }
 ```

**Comment by mtoy-googly-moogly** [comment]
OK, what things are legal in project ...

1) project: [ exisitingFieldName, newName is Expression ]
  * existingFieldName must be an aggregate or a scalar, cannot be a query
  * Expression -- are filtered expressions legal here?
2) where
3) top / order_by / limit

Anything else which is legal. or which should be illegal?

**Comment by mtoy-googly-moogly** [comment]
```
exploreName->{
  project: [
    measureName, // pretty sure this is legal
    newM is measureName * 2, // lloyd seems to indicate this is also legal
    avgM is ANY_AGGREGATE_FUNCT(), // this is non-sensical and illegal, right?
  ]
```

**Comment by lloydtabb** [comment]
Your example says 'measureName', but I think you mean 'dimensionName'.  Right?

**Comment by lloydtabb** [comment]
In your example 

`query: a -> { aggregate: f is count() } -> { project: f2 is f + 1 }`

f is a measure in the first segment
f is a dimension in the second segment (as is f2)

**Comment by lloydtabb** [comment]
I'm curious how come you think f is a measure in the second segment.  If you are asking `malloy_query` for the output structure, it will tell you it is a dimension...

**Comment by mtoy-googly-moogly** [comment]
ok, `project: []` lists need to be like group_by -- scalars and scalar defs only

**Comment by mtoy-googly-moogly** [comment]
I believe this is now (ea8d294c5b7759693293a93d63674e78adcc4528) as fixed as it is going to be. `project:` is a little bit picky about what goes in there, but it could be more picky and when that comes up, we'll file a new bug
