### ISSUE TITLE
How Malloy Handle Multi Fact Tables 

### ISSUE THREAD

**Issue by djouallah** [looker-open-source/malloy#189]
it is not very clear from the documentation,  is the plan to merge the results of two explore, or do you guys recommend joining two fact using multiple to multiple which is rather an expensive operation.

what's the plan exactly ?

**Comment by anikaks** [comment]
Hey @djouallah , can you elaborate a little about what you have in mind here, particularly around joining multiple to multiple? I think the answer depends a little on what one is trying to accomplish specifically.

**Comment by djouallah** [comment]
let's say I have three fact tables, Budget, actual, and target, those three facts don't have the same grain, but share some common dimension, let's say I want to show in the same table three measures, and one common dimension Store
 
Dim Store 
Measure : sum(Budget) from table budget
Measure : sum (sold) from table Actual
Measure  : sum (Target) from Target

how to approach that in Malloy

**Comment by lloydtabb** [comment]
In Malloy, you simply join this data into your explore.  It is the same technique used to build funnels (bunch of joined results on a common attribute or set of attributes).  We don't have an example pattern written for this but you can see how it is done in LookML 

   https://community.looker.com/lookml-5/analytic-block-simple-funnel-279

Malloy can handle aggregates and computations various levels of dimensional granularity simultaneously.   Malloy almost never has to resort to fact tables for computations.  If you joined in the budget and sold in your example you could safely reaggregate these numbers and they would always be computed reltaive to the table they are in, not the rows in the current query.

This is complicated and I hope it makes sense.

**Comment by lloydtabb** [comment]
Closing but happy to continue the conversation.

**Comment by djouallah** [comment]
@lloydtabb Thanks for your help, but I am afraid I don't understand a word :) , can you please provide an example in the documentation  with 3 fact tables with a full Model. 
Thanks.

**Comment by lloydtabb** [comment]
Why do you use dimension/fact tables?  The answer is that aggregates in traditional data warehousing are always computed at some granularity.

No suppose there was a way to compute aggregates where it didn't matter how the data was joined?  You could just join everything and the aggregates would compute magically.  In your example, you could join your target table, your budget table and your actual table and then do *any* aggregate calculation and it would work.

That's how Malloy works.  You don't have to make fact tables in the way other tools do.

This document does a pretty good job of explaining.

https://looker-open-source.github.io/malloy/documentation/language/aggregates.html

**Comment by djouallah** [comment]
@lloydtabb thanks that's a very clear explanation, what  do you do for conformed dimension, I guess you still need them, if I want to show the sum of budget and actual and forecast by all stores.

let's say Budget has store1, store2
            actual has store 2, store 3
           forecast store,store1,store2,store4

I guess full outer join will work, but I need a dimension store with the values 1,2,3,4

**Comment by lloydtabb** [comment]
There are lots of ways to solve this when you aren't worried about data fanning out.

In this case your starting explore might have all the 'conformed dimensions' and you would join in budget, actual and forecst. 

Another example is a wide union.  

  Daniel Mintz talks about it here: https://twitter.com/danielmintz/status/1480352465195356163

**Comment by lloydtabb** [comment]
and This:

https://community.looker.com/lookml-5/outer-join-on-false-or-how-i-learned-to-stop-fanning-out-and-love-the-null-4786

**Comment by djouallah** [comment]
@lloydtabb  with the updated documentation, things started making more sense, Looking forward for a Windows Build :)
