### ISSUE TITLE
Results window looks wonky in dark themes

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#19]
Lindsey encountered this using Spacegray theme in VSCode

![Screen Shot 2021-08-27 at 3 55 49 PM](https://user-images.githubusercontent.com/7178946/131196277-06566c76-52e2-40d6-b2af-fb53326f4180.png)

![image](https://user-images.githubusercontent.com/7178946/131196299-a4542c14-a756-4b30-a9ef-9d16b34a96fd.png)

**Comment by mroyle** [comment]
I found the same thing.  I tend to like working in dark mode, so it can make charts difficult to see

**Comment by christopherswenson** [comment]
Implementation-wise, we can add classes to the DOM elements produced in the renderer, then add a stylesheet in the extension that uses the theme color variables. See https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content
