### ISSUE TITLE
docs files with compile errors

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [looker-open-source/malloy#193]
```
File /language/time-ranges.html compiled in 0.247s.
  !! Error: TypeError: Cannot read property 'pipeHead' of undefined
File /examples/ga_sessions.html compiled in 2.423s.
  !! Error: TypeError: Cannot read property 'pipeHead' of undefined
  ```

**Comment by anikaks** [comment]
@mtoy-googly-moogly I can take a look at this!

**Comment by mtoy-googly-moogly** [comment]
let me know if this is untranslated code or if it is a compiler error

**Comment by anikaks** [comment]
@mtoy-googly-moogly I fixed the ga_sessions one but I'm not seeing that error anywhere on `/language/time-ranges.html`. When/how are you seeing that?

**Comment by anikaks** [comment]
Scratch that. I see the error when I serve the docs, but I cannot figure out what is causing this error. I had seen the same one when docs weren't impressed by a query, but there aren't any runnable queries on this page...
