### ISSUE TITLE
BUG: run icon on schema viewer is now missing

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#240]
<img width="308" alt="Screen Shot 2022-01-24 at 1 38 14 PM" src="https://user-images.githubusercontent.com/7178946/150869175-8ab63819-55d9-460a-8f66-c7bcbf4015c4.png">

there should be a little green play button to click and run a named query

**Comment by christopherswenson** [comment]
Fixed by https://github.com/looker-open-source/malloy/pull/242
