### ISSUE TITLE
update to use real activation events asap

### ISSUE THREAD

**Issue by bporterfield** [looker-open-source/malloy#245]

**Comment by jonathanswenson** [comment]
guessing here, but assuming this is talking about the recent change https://github.com/looker-open-source/malloy/pull/241/files#diff-b86bcd9990a9ff66eea861d61e4c6a1c8f939104de7b12151456c4b97cdeff9cR27 that added `activationEvent: “*”` this seems to be throwing a new warning in compilation of the VS code extension that requires user interaction to complete the build: 

```
 WARNING  Using '*' activation is usually a bad idea as it impacts performance.
More info: https://code.visualstudio.com/api/references/activation-events#Start-up
Do you want to continue? [y/N] y
 DONE  Packaged: /<path>/src/malloy/packages/malloy-vscode/malloy-vscode-0.0.2.vsix (37 files, 1.81MB)
Done in 70.36s.
```
