### ISSUE TITLE
Path not found inventory_id (vscode)

### ISSUE THREAD

**Issue by swuecho** [looker-open-source/malloy#251]
```malloy
query: table('db_name.public.table_name') -> {
  project: [ inventory_id ]
  where: asn_id=11371
}
```

It's great to have compile time check, but the error msg seems not right. I double checked that the 'inventory_id' exists.

**Comment by anikaks** [comment]
Hi @swuecho - your syntax looks right to me at first look. Just to check, have you tried any other fields here, and did they work? has anything else successfully run for you yet?

**Comment by swuecho** [comment]
```
query: table('titan.pg_catalog.pg_tables') -> {
  project: [ tablename ]
  where: tableowner='titan'
}
```
```sh
 select * from titan.pg_catalog.pg_tables where tableowner = 'titan';
```

I tried above malloy query. no luck too. The sql works fine. I can not run anything with postgres yet.

**Comment by anikaks** [comment]
Thanks @swuecho -- what is the datatype  of that field in postgres?

another thing to try - can you try making it an explore and see if it comes up in the schema view? using the example you provided, that would look like:
```malloy
explore: table_name is table('db_name.public.table_name') {}
```
 you can find the schema viewer in the malloy tab on the left. You may need to click into the open file to see it.
<img width="940" alt="Screen Shot 2022-01-24 at 7 45 00 PM" src="https://user-images.githubusercontent.com/7178946/150907182-317f77d3-4aac-4664-9712-695ca2a52aa3.png">

**Comment by swuecho** [comment]
![image](https://user-images.githubusercontent.com/666683/150909982-5633d659-034a-432a-9d82-f66f557026a3.png)

❯ node -v
v17.2.0

**Comment by anikaks** [comment]
@swuecho I'm also hitting a bump querying the pg_catalog tables; looking into this.

In the mean time, was the other query you were trying to run also against pg_catalog? I am wondering if that was a different issue (and hopefully one we can solve quickly!)

**Comment by swuecho** [comment]
If I left the db prefix, `unknown postgres type boolean malloy` will reported. 

and seems wherever the problem is, the error message is always on the first line.

**Comment by anikaks** [comment]
The boolean type is currently not supported in postgres; we're working to get that addressed asap. Lots of booleans in the `pg_catalog` tables which seems to be the cause of our trouble here.

**Comment by swuecho** [comment]
> The boolean type is currently not supported in postgres; we're working to get that addressed asap. Lots of booleans in the `pg_catalog` tables which seems to be the cause of our trouble here.

I see. the tables I query all has boolean type, which is used to make soft delete.

**Comment by anikaks** [comment]
That explains it. we should have a fix for you soon.

**Comment by lloydtabb** [comment]
Added boolean support.  Please not that date/time support is not currently implemented in postgres (should be happening pretty soon).  Postgres support is currently incomplete.

   https://github.com/looker-open-source/malloy/pull/262

**Comment by anikaks** [comment]
Hey @swuecho  - Lloyd's fix which should unblock you went into the marketplace this evening. If you uninstall, quit vscode, then reopen & install, this _should_ have you back in business--let me know if not.

**Comment by swuecho** [comment]
@anikaks works great!
