### ISSUE TITLE
differences in limiting behavior running turtle with and with `reduce` confusing

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#27]
It feels odd to me that these produce differently limited results. 

<img width="616" alt="Screen Shot 2021-09-14 at 6 19 06 PM" src="https://user-images.githubusercontent.com/7178946/133354752-8632ca6c-b829-4d8a-b137-bff9b7526e75.png">

by_state is defined: 
```
by_state is (reduce
    state
    airport_count
```

**Comment by bporterfield** [comment]
almost certainly different nowadays
