### ISSUE TITLE
Adding Python modules in VSCode

### ISSUE THREAD

**Issue by L0kkers** [looker-open-source/malloy#270]
Hello, I have trouble adding modules like numpy, matplotlib or pandas in VSCode.
It all works fine in the original Python (3.10.2) interface, I installed them _via_ the console with pip.
Anytime I type   "import x"   it says   "ModuleNotFoundError: No module named 'x'".
Have I missed something when setting up VSCode ?

**Comment by lloydtabb** [comment]
Sorry, this isn't related to Malloy.
