### ISSUE TITLE
Error on empty .malloy files

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#271]
I get an error when I have nothing in a .malloy file, but it doesn't seem to mind if there's stuff there but just commented out. Not sure if there's a reason not to do this, but I think having an immediate error when you create a file is a bit off-putting (plus the error persists if you delete said file), and ideally we could just accept empty models. 
no model:
<img width="814" alt="Screen Shot 2022-01-25 at 4 45 43 PM" src="https://user-images.githubusercontent.com/7178946/151084186-adb3d2b6-8489-41d4-b023-1884342e2ad1.png">

commented model:
<img width="542" alt="Screen Shot 2022-01-25 at 4 45 35 PM" src="https://user-images.githubusercontent.com/7178946/151084214-060f85df-d6f1-41c1-9425-e511ef61b0e6.png">

**Comment by mtoy-googly-moogly** [comment]
So a file with no statements in it is legal, and if you parse a file containing a single newline, everything works fine, but if you parse a file containing no characters, ANTLR refuses to return a parser.

I'll hack around it by parsing "" as "\n"

**Comment by mtoy-googly-moogly** [comment]
Good catch @anikaks ! All fixed.
