### ISSUE TITLE
Run | Render -> Run| SQL|Render

### ISSUE THREAD

**Issue by swuecho** [looker-open-source/malloy#273]
![image](https://user-images.githubusercontent.com/666683/151124165-412612c2-a637-4af4-8ca6-40382f740493.png)

similar to  the HTML|JSON|SQL tab feature in html.

especially, for learning and debug purpose, SQL is important.

**Comment by swuecho** [comment]
BTW, I assume generate the html report from malloy file is automated. Is there a tutorial on it?

**Comment by lloydtabb** [comment]
Yes, I agree that seeing the SQL is really important. Tagging  @christopherswenson.

You see this today but it is a little hidden.  Open the 'Output' Window and set the output to 'Malloy'.

![image](https://user-images.githubusercontent.com/1093458/151172674-594d0b9d-5d58-4553-b78f-f4ddb13c31bf.png)

If you pull the repository, the documentation is built by running 'docs-build'.  Documentation on how to setup the development environment below.

https://github.com/looker-open-source/malloy/blob/main/documentation.md

**Comment by anikaks** [comment]
> BTW, I assume generate html report from malloy file is automated. Is there a tutorial on it?

The "Render" code lens currently renders a table, or if you've set up any styles, it renders a visualization. [This doc](https://looker-open-source.github.io/malloy/documentation/visualizations/dashboards.html) covers the options and how to work with data styles; the Rendering section in docs also has specific write-ups on several vis types.

**Comment by swuecho** [comment]
fantastic! Thanks!
