### ISSUE TITLE
would love a windows version of the vscode extension

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [looker-open-source/malloy#279]

**Comment by djouallah** [comment]
come on we are people too :)

**Comment by nryberg** [comment]
What can we do to build this in VSCode for Windows 64bit?

**Comment by lloydtabb** [comment]
To make it part of the project we'd have to first make it work and then figure out how to do continuous integration.  We're all using linux and Mac to do our development and a pretty small team. We verify on Linux.   You could fork the repo and see what it takes to make it work.  I'm really sorry we don't have the bandwidth to do this at the moment.

**Comment by bporterfield** [comment]
The tasks would be:

1. Build extension on windows and deal with any existing pathing/filename/etc issues we've introduced that breaks on windows (unknown effort)
2. Change build process to include keytar native modules for various windows archs (small task)
3. Change publish process to publish new windows flavors (small task)
4. Ensure CI tests on windows (medium task)

If anyone can accomplish #1 above, we could probably handle the rest

**Comment by bporterfield** [comment]
@djouallah @nryberg the latest version of the VSCode Extension now supports windows x64 - please take a look!

**Comment by bporterfield** [comment]
Sorry, to clarify - in the *pre-release* version of the extension. This requires selecting "install pre-release" from the install dropdown.
