### ISSUE TITLE
Refinement Field lists are in the wrong order.

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#310]
When you merge queries using refinements, I think you have the source and destination backward, but it may be just the field list.  I would expect the output field order to be `state, airport_count, by_fac_type`

```
explore: airports is table('malloy-data.faa.airports') {
  measure: airport_count is count()

  query: by_state is {
    where: state != null
    group_by: state
    aggregate: airport_count
  }

  query: by_fac_type is {
    group_by: fac_type
    aggregate: [
      airport_count
      avg_elevation is elevation.avg()
    ]
  }
}

query: airports -> by_state {
  nest: by_fac_type
}
```

Generates

![image](https://user-images.githubusercontent.com/1093458/151955668-24fd8aab-b2c2-4059-b1e3-78ef8c238700.png)

**Comment by mtoy-googly-moogly** [comment]
It was #2 --- I did a clean and then a build and now I get

![image](https://user-images.githubusercontent.com/66150587/152026213-57fff6ad-5ac1-4873-8252-3c397bd60178.png)
