### ISSUE TITLE
Implement date_diff

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#315]
We're currently choking on the timeframes when trying to use BigQuery's date_diff (https://github.com/looker-open-source/malloy/issues/47 is a more general issue around that), chatted with Lloyd and sound like we should just have our own implemented date_diff.

**Comment by anikaks** [comment]
This came up twice today. 
1) I was trying to do "days between x and y dates" and hit the same issue. 
2) shortly thereafter, as user ran into this, expecting subtracting two dates to perform a datediff (as it does in postgres).

**Comment by anikaks** [comment]
Workaround, for now:
```malloy
dimension: days_to_ship is UNIX_DATE(`DATE`(shipped_at))::number - UNIX_DATE(`DATE`(created_at))::number
dimension: hours_to_ship is (UNIX_SECONDS(`timestamp`(shipped_at))::number - UNIX_SECONDS(`timestamp`(created_at))::number)/3600
```

**Comment by mtoy-googly-moogly** [comment]
... and subtracting things doesn't actually do a date diff ... 

it creates an interval,  which is only useful for knowing how many seconds, minutes, hours or days there are between two dates and will fail spectacularly if you want to know weeks or months, for weird reasons having to do with the interval type.

... and in Malloy, everything works without you having to think about it.
