### ISSUE TITLE
Antlr grammar build sometimes gets out of sync

### ISSUE THREAD

**Issue by christopherswenson** [looker-open-source/malloy#336]
Not sure what causes this, but sometimes you need a `yarn clean` because `yarn build` fails due to antlr thinking it doesn't need to rebuild when it actually does.

**Comment by bporterfield** [comment]
Perhaps from @mtoy-googly-moogly recent changes to cache lang builds? 

https://github.com/looker-open-source/malloy/blob/main/packages/malloy/src/lang/grammar/build-parser.sh

**Comment by mtoy-googly-moogly** [comment]
I was trying to fix "rebuilds the grammar every time" problem.

If after @aryeh-looker merges the stupid fix to running on Linux, and this still happens, let me know.

Basically we only regenerate the parser when the md5 hash of the grammar file changes, or if the parse isn't there.

This should be pretty foolproof, super happy to chase down bugs. Tar me up "packages/malloy/lang" form your tree if you see this so I can diagnose why it isn't deciding to rebuild.

**Comment by mtoy-googly-moogly** [comment]
Going to leave this open for a week and if nobody drops me a tar, I'll close it.

**Comment by mtoy-googly-moogly** [comment]
just merged the fix ... let me know if you see this problem again

**Comment by mtoy-googly-moogly** [comment]
Feels fixed, closing.
