### ISSUE TITLE
When using `with` join syntax, cannot use a foreign key that's nested or accessed with `.`

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#347]
It seems that `with` isn't accepting `.` in joins

this is erroring:
```malloy
explore: products is table('malloy-data.ecomm.products')

explore: inventory_items is table('malloy-data.ecomm.inventory_items')

explore: order_items_test is table('malloy-data.ecomm.order_items'){
  join_one: inventory_items with inventory_item_id
  join_one: products with inventory_items.product_id
}
```

`extraneous input '.' expecting {ACCEPT, DIMENSION, EXCEPT, JOIN_CROSS, JOIN_ONE, JOIN_MANY, MEASURE, PRIMARY_KEY, QUERY, RENAME, WHERE, '}', ';'}`

<img width="654" alt="Screen Shot 2022-02-04 at 3 04 03 PM" src="https://user-images.githubusercontent.com/7178946/152614677-737bb4df-4808-4b55-8c63-cba77544f677.png">

but if I write out the join with `on` instead of using the shorter `with` syntax it's happy:
```malloy
explore: order_items_test is table('malloy-data.ecomm.order_items'){
  join_one: inventory_items with inventory_item_id
  join_one: products on inventory_items.product_id = products.id
}
```

**Comment by mtoy-googly-moogly** [comment]
this is by design ... anything other than a simple key that is in the outer explore introduces problems.

**Comment by mtoy-googly-moogly** [comment]
I thought this was what @lloydtabb wanted ... I await instructions.

**Comment by anikaks** [comment]
@lloydtabb can you confirm?

**Comment by mtoy-googly-moogly** [comment]
I talked with @lloydtabb and you are correct @anikaks -- we should allow this.

**Comment by mtoy-googly-moogly** [comment]
@lloydtabb so i have the code now which would return
```
...
  structRelationship: {
    type: "foreignKey",
    foreignKey: "inventory_items.product_id",
  }
```

Is that correct?
