### ISSUE TITLE
References to fields inside nested queries are not checked properly

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#373]
The following should work.  I'm getting `q cannot contain a state` error.

```
explore: airport is table('malloytest.airports') {
  query: by_region is {
    limit: 10
    group_by: faa_region
  }

  query: by_region2 is  by_region {
    nest: q is {
      group_by: state
    }
  } 
  -> { 
    project: [faa_region, q.state ]
  }
}

query: airports -> by_region2
```

**Comment by mtoy-googly-moogly** [comment]
Yeah this is trying to make "q.state" and not having access to that in the namespace-object. Looking at it.

**Comment by mtoy-googly-moogly** [comment]
I could maybe just let through unchecked any string of references after a nested query and let the SQL generator figure that out.

**Comment by mtoy-googly-moogly** [comment]
I could also turn off reference checking entirely if it was a bad idea.

**Comment by lloydtabb** [comment]
> I could maybe just let through unchecked any string of references after a nested query and let the SQL generator figure that out.

I'll catch the error before it goes to SQL with my infamous path not found error.  I think we are in the land of 'Good Enough' for now.  The reference checking is pretty great.  

I can also build something that validates nested pipelines in StructDefs after the fact.  It would be pretty efficient...

**Comment by mtoy-googly-moogly** [comment]
Turns out I was wrong ... the problem was not a turtle ref, the problem was when you create a new turtle by adding queries to the old one, it forgot to walk the old one to get the output struct before trying to compile the new one.
