### ISSUE TITLE
Unknown Dialect error on Unknown Join

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#374]
When you attempt to join something and the source is unknown you get an `Unknown Dialect` error instead of an unknown join.

![image](https://user-images.githubusercontent.com/1093458/153759945-25145036-f32e-4f3c-8981-e6acedbe7e93.png)

```
explore: flights is table('malloy-data.faa.flights') {
 join_one: carriers with carrier
}
```

**Comment by mtoy-googly-moogly** [comment]
OK, the error now highlights properly (there's been a bunch of work on errors in the last week). I could never repro the unknown dialect problem. Re-open if you get a reproducible case.
