### ISSUE TITLE
pick is too picky about types -- NULL should match all types

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#49]
per @mtoy-googly-moogly : `pick when true then 'a' else NULL` will error because pick wants all values to be compatible and it isn't very smart

**Comment by mtoy-googly-moogly** [comment]
OK, I can't find what we meant by this:

```
  pick 'a' when 1=1
  else NULL
```

compiles fine. @anikaks do you remember what we meant by this or maybe this was never a bug?

**Comment by anikaks** [comment]
Found an example; this was on the old syntax and apparently gave an error at one time:
```
order_items | reduce
    status
    new_status :
        pick when 'Complete' | 'Processing'
        else NULL  
```

However this now seems to run just fine so seemingly no longer an issue?
```
query: table('malloy-data.ecomm.order_items') -> {
  group_by: status
  group_by: new_status is status:
        pick when 'Complete' | 'Processing'
        else NULL  
}
```

**Comment by mtoy-googly-moogly** [comment]
Ah, yeah, I think maybe that got fixed as a side effect of the other pick fixes I made. Thanks for checking!
