### ISSUE TITLE
VS Code Extension running wrong query with multi-stage pipeline using named queries

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#498]
Given this:
```
source: flights is table('malloy-data.faa.flights'){
  measure: flight_count is count()
}

query: flights_base is flights -> {
  aggregate: flight_count
  nest: main_query is {
    group_by: carrier
    aggregate: flight_count
  }
}

query: flights_percent is -> flights_base -> {
  project:
    main_query.*
    flight_count_as_a_percent_of_total is main_query.flight_count / flight_count * 100.0
  }
  ```

When I click the "Run" lens on `flights_base`, `flights_percent` runs instead. If I comment out `flights_percent`, the correct query runs.

Not sure if this is a language or VS Code extension issue so tagging both @mtoy-googly-moogly and @christopherswenson

**Comment by whscullin** [comment]
@mtoy-googly-moogly this seems to be a language issue - the compiler is returning the `flights_percent` stage even though the block structure would imply that it is separate. 

The result of QueryModel.compileQuery() in the commented out case
https://gist.github.com/whscullin/a7a7aa69e1788edd7fac401b8128e991
vs not commented out.
https://gist.github.com/whscullin/adbe95465678242eb9abd2f5b736341b

query.name is `flights_base` in both instances.

**Comment by mtoy-googly-moogly** [comment]
Yeah this looks like a failure to clone a query when it is being used as the basis for a second query ... should be easy to fix
