### ISSUE TITLE
Improve "raw" error location references

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#51]
based on @mtoy-googly-moogly :
>The errors in the edit window are problem. There are "raw" errors, with code locations and error messges, and "cooked errors" which are only really useful in a terminal, and it looks like the editor is displaying the cooked errors?
>
>What is not yet accurate in the "raw" errors are the code locations. Was waiting for someone to need that.

**Comment by mtoy-googly-moogly** [comment]
This is pretty much baked into the language now. I'm closing and would like code samples for specific phrases where the error messages are not located properly.
