### ISSUE TITLE
Error: `Unknown Dialect ~malformed~` when redefining a source already defined in an imported file

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#511]
I defined a source `airports` in one file, imported this file into a second file, and accidentally defined a source in this file also named `airports`. Error was unhelpful and did not show the area causing the problem. 
<img width="736" alt="Screen Shot 2022-04-26 at 8 02 02 PM" src="https://user-images.githubusercontent.com/7178946/165431384-aa964408-7698-4f35-9376-86513e3a3b0c.png">

**Comment by mtoy-googly-moogly** [comment]
Every time this happens, what has happened is that the compiler has generated an error, but as it continues to parse the rest of the file, it does something which generates an exception, which means the error which is in the error log is never reported. I'll fix this one. Thanks.

**Comment by mtoy-googly-moogly** [comment]
I can't repro this, I get "Cannot redefine 'airports'" and then a warning about airports using `:` and not `?` and then an unformatted dump of the error array in the preview window

**Comment by mtoy-googly-moogly** [comment]
![image](https://user-images.githubusercontent.com/66150587/165635245-8fe053b9-8c62-4955-b8a7-be0a626c26d8.png)

**Comment by mtoy-googly-moogly** [comment]
I need a reproducible case, my attempt to repro from the screen shot has failed.

**Comment by mtoy-googly-moogly** [comment]
I have fixed some of these types of errors, it is possible that this will go away if you run something newer.

**Comment by anikaks** [comment]
I'm also now unable to reproduce since updating to the brand new pre-release. Sorry about that--marking resolved!
