### ISSUE TITLE
Allow testing only one dialect

### ISSUE THREAD

**Issue by greg-finley** [looker-open-source/malloy#518]
As more dialects are added, external contributors might be interested in fixing something with one dialect and might not even have access to the others (i.e. BigQuery, Snowflake, etc.). It would be great if they could easily test their one dialect.

The interface could be `yarn test-postgres` or `yarn test --dialect=postgres` or something.

**Comment by mtoy-googly-moogly** [comment]
Yup, our testing "framework" is "barely enough framework to run tests".

We don't really have a generic framework for running tests against multiple dialects. Each spec file has come copy pasted code which runs against a static list of dialect. I'd love to see us formalize this. Once that is in place, it totally makes sense to have some way to control the list .. environment variables, package configs, command line options.

**Comment by greg-finley** [comment]
That's an interesting idea! I guess it would recompute the cache on merges to `main` in case of bug fixes? It would be great if `test-db-cache.lock` is updated by the CI pipeline. Agree that it might be better to use a file for an open-source project.

**Comment by mtoy-googly-moogly** [comment]
I am not sure how the maintenance of the file would work. My guess was there is a manual step to update it like you would do with the package lock file, but maybe it makes sense for CI to maintain it instead.

**Comment by mtoy-googly-moogly** [comment]
No objections to something quick and dirty for now though, like a command or environment variable, if you are running into this problem yourself. If you are just worried about theoretical future people, then I want to think about doing the more complex but possibly better thing.

**Comment by greg-finley** [comment]
Yeah I am liking the cache idea. I personally can run BQ via a personal project, but maybe not Redshift, Snowflake, etc.
