### ISSUE TITLE
Outside developers cannot see CI output

### ISSUE THREAD

**Issue by greg-finley** [looker-open-source/malloy#530]
Most (all?) open-source projects I've seen will let an outside contributor see the CI output. However, this project's commits have a link like `View more details on Google Cloud Build` but the output is not publicly visible.

![Screen Shot 2022-05-05 at 9 01 53 AM](https://user-images.githubusercontent.com/28961086/166964750-91ea042d-632e-4fa6-a0f8-daa66330c0ac.png)

**Comment by bporterfield** [comment]
This is resolved, for folks trying to contribute we can provide an access level that shows output.
