### ISSUE TITLE
DuckDB: figure out how pass along a directory to find files

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#555]
Hannes suggested reading up on this:

Hannes Mühleisen5:37 AM
https://github.com/rilldata/rill-developer
Hannes Mühleisen5:49 AM
https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L491
https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/src/pyconnection.cpp#L539
Hannes Mühleisen5:53 AM
https://pubs.opengroup.org/onlinepubs/009695299/functions/access.html

**Comment by bporterfield** [comment]
@lloydtabb this is complete, yes?

**Comment by lloydtabb** [comment]
Done.
