### ISSUE TITLE
Support for databricks sql via jdbc/odbc

### ISSUE THREAD

**Issue by pm-hwks** [looker-open-source/malloy#587]
Any plans or i can build one with guidance...

**Comment by lloydtabb** [comment]
We don't have plans at the moment.   Support for SQL dialects can be really complex in that they all handle nested data quite differently.  We currently support Standard SQL, DuckDB and Postgres.   Each of these was a lot of work and a lot of nuance.  I don't have the cycles at the moment to take on another.

**Comment by bporterfield** [comment]
We cannot - support for ANSI SQL does not (at least, today) imply Malloy will be functional - we have to build each dialect independently, as support depends on many factors. For example, [here](https://github.com/looker-open-source/malloy/blob/main/packages/malloy/src/dialect/postgres.ts) is the postgres dialect support - note that many features utilized are not part of ANSI SQL.

Will put in a vote for databricks as a future dialect 👍
