### ISSUE TITLE
Measure Builder UI

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#604]
The most common measures are, count(), count(field), field.sum(), field.avg().  The measure build should show you a list of fields and then choose the function to apply to the field and have an option to make a custom measure.

**Comment by djouallah** [comment]
sum cumulative too :), ratio compared to the total

**Comment by djouallah** [comment]
another very common pattern is something like 
sum (x) filter (y = 5)
sum (x) filter (y > 5)

this one is tricky but very useful
for example sum(x) all , it will return the sum regardless of any filters or any grouping.

**Comment by lloydtabb** [comment]
^^ this is already supported.  See example below.

https://looker-open-source.github.io/malloy/documentation/patterns/yoy.html

**Comment by lloydtabb** [comment]
We are looking at something different for the ungrouped aggregate computations and filters should apply.  Shouldn't be limited to SUM.  

it might look something like.

```
measure: 
   sales is revenue.sum()
  percent_of_sales is sales/total(sales)

query: by_product is {
  group_by: product.name, product.id
  aggregate: sales, percent_of_sales
}
```
