### ISSUE TITLE
DuckDB in Windows does not work

### ISSUE THREAD

**Issue by djouallah** [looker-open-source/malloy#619]
BigQuery example works fine, but when I tried DuckDB, using this example

```
source: names_table is table('duckdb:data/usa_names.parquet') {
  measure: population is `number`.sum()
  dimension: decade is floor(`year`/10)*10
```
i get 
unknown dialect, malformed

**Comment by gmaden** [comment]
I am able to reproduce this. It looks like this is an issue related to our relative pathing for DuckDB on Windows. And that coupled with a not so helpful error message for the user.
You should be able to work around it in the meantime by specifying the full path to the parquet file.

**Comment by djouallah** [comment]
how, I don't know how to use Quotation etc

```
source: names_table is table("duckdb:C:/Users/mimoune.djouallah/Desktop/malloy/duck/data/usa_names.parquet") {
  measure: population is `number`.sum()
  dimension: decade is floor(`year`/10)*10
```

**Comment by gmaden** [comment]
Ah yes I suppose that points out another limitation on the handling of absolute paths since ':' is a special character. In theory since you're just using the default C:\ you should be able to omit that and use something like:
```
source: names_table is table("duckdb:/Users/mimoune.djouallah/Desktop/malloy/duck/data/usa_names.parquet") {
  measure: population is `number`.sum()
  dimension: decade is floor(`year`/10)*10
```

Or there is the more verbose solution if you needed to access a different drive/share
```
source: names_table is table("duckdb://localhost/c$/Users/mimoune.djouallah/Desktop/malloy/duck/data/usa_names.parquet") {
  measure: population is `number`.sum()
  dimension: decade is floor(`year`/10)*10
```

**Comment by djouallah** [comment]
yep, tried first option it works, thanks !!!! u are awesome !!!
