### ISSUE TITLE
Feature request : Syntax sugar get rid of where clause to pass filters in measures

### ISSUE THREAD

**Issue by djouallah** [looker-open-source/malloy#628]
to pass a filter to a measure, we write something like this 

`Quantity_RETURNFLAG_A is Quantity { where:  L_RETURNFLAG = 'A' }`

can we get rid of " where:", , as a DAX user, it feels more readable. 

Quantity_RETURNFLAG_A is Quantity { L_RETURNFLAG = 'A' }

**Comment by lloydtabb** [comment]
Already here :) but slightly different.

```
 Quantity_RETURNFLAG_A is Quantity {? L_RETURNFLAG = 'A' }
```

**Comment by djouallah** [comment]
ah, it is not the same , trying to give a different perspective, this little thing matter a lot for average user ;)

**Comment by lloydtabb** [comment]
I really appreciate your perspective.  Please don't stop making suggestions.  It is always good to hear what you were expecting.
