### ISSUE TITLE
Query Crashes VSCode

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#670]
This query fails but runs fine from the duckdb command line.  I suspect it might have something to do with the node interface, but I really have no idea.  Uses the names data.  

The query works fine with a smaller amount of data.  I don't think we're running out of memory, but maybe ???  It would be great not to crash and to have an error message at least.

```
source: names is table('duckdb:data/usa_names.parquet') {
    measure: population is `number`.sum()
    dimension: decade is floor(`year`/10)*10

  query: name_dashboard_rendered is {
    group_by: name
    aggregate: 
      population
    nest: state_popularity_shape_map is {
      group_by: state
      aggregate:
        births_per_100k is 
          population / 
          exclude(population,name) * 100000
    }
    nest: by_decade_line_chart is {
      group_by: decade 
      aggregate: population
    }
    limit: 10
  }
}

```

**Comment by whscullin** [comment]
Interestingly it works for me on macOS. It crashes if I use remote VSCode, but local Linux gives me
```
INTERNAL Error: INTERNAL Error: Assertion triggered in file "../src/duckdb.cpp" on line 55418: FlatVector::Validity(result).CheckAllValid(count)
```

**Comment by whscullin** [comment]
I've kind of hit the wall with this. I can't create a non-vscode repro, and debugging within vscode is a no-go. I think the fix for this will wind up being forking duckdb processes so we at least have some control over the process lifespan.

**Comment by whscullin** [comment]
Closed by https://github.com/looker-open-source/malloy/pull/731
