### ISSUE TITLE
In Shape Maps, the color palette seems too subtle.  

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#671]
Can we get a wider range pallet to make the differences more visable?

Run the malloy_team query in names_3.malloy

![image](https://user-images.githubusercontent.com/1093458/181917550-7c8324b0-95ca-4423-9f55-d79dc2fab2b3.png)

**Comment by whscullin** [comment]
Red to green is a classic - other thoughts?

**Comment by whscullin** [comment]
Here's our current pastel gradient that we use for charts (the non-pastel version hurts my eyes):
<img width="614" alt="Screen Shot 2022-08-01 at 10 33 24 AM" src="https://user-images.githubusercontent.com/2958002/182208533-a0cc9358-bc94-4dbc-ae74-26535d90ce15.png">

**Comment by anikaks** [comment]
I like what you did with the contrast! If we go the red/green route, I think I've read that you can use magenta + green to be slightly friendlier to red-green color blindness

**Comment by tschomer** [comment]
I've done a TON of research into this, while working on the Looker color palettes. We need to keep things single-color, starting lighter, and ending darker - until we get some smarts put in for divergent color setups (negative-to-zero-to-positive). Multiple colors don't work for the regular case because you can't tell what the colors mean. :-)

**Comment by tschomer** [comment]
![colors](https://user-images.githubusercontent.com/40474956/182255917-75fd76fc-e14a-4fbb-b7e5-9325b9bced47.png)
looker palettes...

**Comment by whscullin** [comment]
For now we landed on light blue to dark blue. The larger issue of reworking our visualizations to be more friendly remains open for now.

<img width="1021" alt="Screen Shot 2022-08-01 at 2 28 15 PM" src="https://user-images.githubusercontent.com/2958002/182249680-a13a6933-0b2f-45aa-9539-19ee3733706e.png">
