### ISSUE TITLE
VSCode:  Nothing works unless there is a duckdb connection

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#680]
It is really confusing to download the extension and try to run something and getting an error.  We need to have both the DuckDb and BigQuery connections installed by default.

**Comment by whscullin** [comment]
It appears this was working as intended, but other things were making it look this it wasn't. Created https://github.com/looker-open-source/malloy/pull/683 to _always_ create bigquery connection if there is none, not just if there is no connections. This means we should handle unconfigured bigquery connections better - see https://github.com/looker-open-source/malloy/issues/580
