### ISSUE TITLE
Need a way of overrriding the Bytes Queries limit in BigQuery.

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#697]
Maybe an environment variable?

When you are developing you may want to do this just temporarily.  

I think we'll need it in the connection configuration as well as an override.

I'd like this asap as someone is hitting this (and it appears there may be a BigQuery mis-estimation bug that makes this happen sooner than we would like.

https://app.slack.com/client/T025JAK7WS2/C025JAK8G0N/thread/C025JAK8G0N-1659497512.965079

**Comment by whscullin** [comment]
Adding a config panel option is easy, environment variables are kind of weird with VSCode because what environment it picks up depends on how you launch it.
