### ISSUE TITLE
declare keyword does not syntax highlight in VSCode

### ISSUE THREAD

**Issue by christopherswenson** [looker-open-source/malloy#706]

**Comment by christopherswenson** [comment]
I'm not sure where we landed on this last... I think we decided we were going to try it out and see how it felt. Saw it in the wild in one of the sample projects today, and it was not syntax highlighted. It still feels ugly to me.

**Comment by anikaks** [comment]
Oh yes I was going to ask about that. I am using and enjoy `declare` and it's crept into our documentation; I'd be in favor of syntax highlighting it

**Comment by anikaks** [comment]
I'd love to see us fix this for now as it looks bad and we have examples using `declare`, even as we continue conversations about declare's place in the language.
