### ISSUE TITLE
Query links for Composer in readme files look ugly when viewed using a normal markdown viewer

### ISSUE THREAD

**Issue by christopherswenson** [looker-open-source/malloy#712]
For Malloy model Readme files, I initially made the syntax look like this:

```
:malloy-query{ model="./model.malloy" query="query_name" source="source_name" }
```

In the Malloy Composer, this would render however we wanted, e.g. a monospace link that opens up the query:

[`query_name`]()

However, in any "normal" markdown viewer, e.g. GitHub or VSCode, that code renders like this:

:malloy-query{ model="./model.malloy" query="query_name" source="source_name" }

This is ugly.

Alternatively, we could write code like:

```
[`query_name`](malloy://model.malloy/source_name/query_name)
```

Which would render like this in both VSCode/GitHub as well as Composer:

[`query_name`]()

However, the link would not work anywhere except Composer. It does not seem to be possible to register a URL scheme inside a VSCode extension to make this link do anything, even in VSCode. Only way to make a link like that work is to install an app on the OS that registers the URL scheme.

Another possibility would be to have a comment preceding a code span, and the comment configures how the code span is to be rendered. 

So the markdown code would look like this:

```
<!--malloy-query model="model.malloy" source="source_name" query="query_name"-->
`query_name`
```

And it would render like this in VSCode and GitHub:

`query_name`

And like this (or however we wanted) in Composer:

[`query_name`]()

It seems like this method would still be usable in titles and inside paragraphs, e.g.:

```
## Title <!--malloy-query model="model.malloy" source="source_name" query="query_name"--> `query_name`
Paragraph <!--malloy-query model="model.malloy" source="source_name" query="query_name"--> `query_name`
```

## Title  `query_name`
Paragraph  `query_name`

For that matter, we could do the same thing for Malloy docs snippets. Instead of putting the run parameters inside the code block in a Malloy comment, we could put them inside an HTML comment outside the code block.

The code today looks like this:

~~~
```malloy
--! {"isRunnable": true, "runMode": "auto", "source": "faa/flights.malloy"}
query: flights -> {
  aggregate: total_distance is sum(distance)
}
```
~~~

Which renders like this in GitHub and VSCode:

```malloy
--! {"isRunnable": true, "runMode": "auto", "source": "faa/flights.malloy"}
query: flights -> {
  aggregate: total_distance is sum(distance)
}
```

And using this technique, the code would become this:

~~~
<!--malloy-snippet isRunnable runMode="auto" source="faa/flights.malloy" -->
```malloy
query: flights -> {
  aggregate: total_distance is sum(distance)
}
```
~~~

Which renders like this in GitHub and VSCode:

```malloy
query: flights -> {
  aggregate: total_distance is sum(distance)
}
```

This would be achievable using a different remark/unified plugin other than `remark-directive`. I'm not sure if one exists, but there is a library called `mdast-comment-marker`, and it should be possible to use that to create a plugin without too much trouble. An example of a plugin making use of `mdast-comment-marker` is [here](https://github.com/remarkjs/remark-comment-config/blob/main/index.js).

**Comment by christopherswenson** [comment]
@anikaks @lloydtabb Can you tell me your thoughts on this?

**Comment by anikaks** [comment]
The first 2 options seem to look or behave badly somewhere and the 3rd doesn't seem to look or behave badly anywhere so I'm in favor of that!

**Comment by christopherswenson** [comment]
This is a test:

 `query_name`

<div>Foo</div> `query_name`
