### ISSUE TITLE
Can you make an NPM package

### ISSUE THREAD

**Issue by domoritz** [looker-open-source/malloy#728]
It looks like Malloy is written in TS and could maybe run entirely in the browser. Would you be able to Rae an NPM package that we can then use to compile Malloy to SQL to run queries against e.,g,. duckdb-wasm entirely in the browser? I think it would be awesome to have the full workflow running the browser.

**Comment by whscullin** [comment]
I looked into the duckdb wasm package a while back, right now it's very much targeting browsers, so it doesn't work in the node contexts that we typically run it in.

**Comment by slopp** [comment]
I would be interested, just for fun, in exploring if a npm malloy package would be compatible with observablehq, as a way to get a notebook interface and significant visualization options available for malloy users.

**Comment by bporterfield** [comment]
Docs are extremely limited, but we have packaged these - you can find working examples of how we use these in our vscode-extension/ folder

https://www.npmjs.com/package/@malloydata/malloy
https://www.npmjs.com/package/@malloydata/db-bigquery
https://www.npmjs.com/package/@malloydata/db-postgres
https://www.npmjs.com/package/@malloydata/db-duckdb
https://www.npmjs.com/package/@malloydata/render
