### ISSUE TITLE
Make Drill in VS Code more intuitive

### ISSUE THREAD

**Issue by djouallah** [looker-open-source/malloy#742]
not sure I understand what does drill do exactly in Malloy UI ?

**Comment by anikaks** [comment]
Hey @djouallah - yeah we need to document this one, and figure out how to make the behavior more intuitive too. 

In VS Code, what it does it copy to your clipboard a source with filters that will allow you to "drill" into the row you selected. From here you complete the query to "drill," using fields, other named queries, whatever you like.

So in this gif, I look at top categories, then by clicking on the "drill" for the "Jeans" row, I get a query that will return whatever fields, queries, etc I want, specific to Jeans. in this case, I drill in using some named queries.

![drilling](https://user-images.githubusercontent.com/7178946/184733266-c50461c2-0d03-49aa-9c0d-e10d311ab827.gif)


Here's one drilling into multiple grouped fields, then drilling in using specific fields.
![drilling2](https://user-images.githubusercontent.com/7178946/184733845-bd762377-fd7b-4b2d-adf6-67b49e59b778.gif)

**Comment by bporterfield** [comment]
Closing until we re-add drilling :D
