### ISSUE TITLE
build doesn't work with yarn 3

### ISSUE THREAD

**Issue by popmonkey** [looker-open-source/malloy#745]
just an FYI because `berry` yarn 3 is pre-packaged with node `16.10` and beyond via their `corepack`.

yarn 3 doesn't have the `license` command so the build breaks here:
https://github.com/looker-open-source/malloy/blob/ab01aa24bce72d591366d658131acd308ddcfaea/demo/malloy-demo-composer/scripts/package.ts#L38

**Comment by bporterfield** [comment]
Moved to npm :D
