### ISSUE TITLE
times rendering as NaN in Fiddle.

### ISSUE THREAD

**Issue by lloydtabb** [looker-open-source/malloy#794]
https://looker-open-source.github.io/malloy/fiddle/index.html?q=2+-+Flights+Table&t=&m=Flights

![image](https://user-images.githubusercontent.com/1093458/189126900-e1aa5ba2-9b29-4b1f-80d9-77551f6c5fbb.png)

**Comment by whscullin** [comment]
Timestamps in duckdb-wasm are represented by number of milliseconds, the logic for returning a value from a `DataTimestamp` object is doing something I don't quite understand, the `typeof this._value !== "string"` conditional is capturing numbers and attempting to deference them, so maybe we need a prior conditional to capture numeric values.

```typescript
public get value(): Date {
    // TODO properly map the data from BQ/Postgres types
    if (this._value instanceof Date) {
      return this._value;
    } else if (typeof this._value !== "string") {
      return new Date((this._value as unknown as { value: string }).value);
    } else {
      return new Date(super.value);
    }
  }
```
