### ISSUE TITLE
internal error path not found with joining of query based source

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#800]
```
INTERNAL ERROR model/Segment.nextStructDef: Path not found prod_b_2.product
QUERY: {
  type: 'reduce',
  fields: [ 'prod_b_2.product' ],
  filterList: []
}malloy
```

Will send along repro model to you @mtoy-googly-moogly !

**Comment by mtoy-googly-moogly** [comment]
I was going to give this a quick look, but I have lost the ability to debug the extension while it runs, and so I cannot look at it today, and then I am gone for a week, which is a problem for a user who loves us. Someone else should pick this up. Ask @anikaks for the files you need to repro this.

If there is no hurry, I will be happy to look at this in small pieces over the next week.

**Comment by lloydtabb** [comment]
Finally, here is a small test case.  If you look at the schema, d isn't named right (it is named a).

```
source: a is from(table('malloytest.state_facts')->{
  group_by: state
  nest: n is {
    group_by: v is airport_count
  }
}) 

source: c is a {
  join_one: d is a on state=d.state
  query: foo is {
    group_by: d.n.v
  }
}
```

**Comment by lloydtabb** [comment]
interestingly, this query works (and the output should be this)

```
source: a is from(table('malloytest.state_facts')->{
  group_by: state
  nest: n is {
    group_by: v is airport_count
  }
}) 

source: c is a {
  join_one: a on state=a.state
  query: foo is {
    group_by: a.n.v
  }
}
```

**Comment by mtoy-googly-moogly** [comment]
The problem was that a query source had `name: "result", as: "nameOfSource"` re-naming this in the join was not clearing the `as:`
