### ISSUE TITLE
Docs search should include code blocks

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#817]
Currently, our docs search does not look at code blocks. This means that folks will search for expressions and not find them. For example, today `concat()` came up - the word only appears within code blocks, and so their search returned no results even though it's in our docs in a couple places. This would make the Expressions, SQL to Malloy, and Examples in docs far more useful from a search perspective.

**Comment by anikaks** [comment]
@christopherswenson I can't remember why it's currently excluded, do you have context here and a sense of whether it would be easy to add in?

**Comment by christopherswenson** [comment]
Fixed by https://github.com/looker-open-source/malloy/pull/840
