### ISSUE TITLE
deploy-prerelease-extension "fails"

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [looker-open-source/malloy#839]
Every time main changes a trigger fires and cloudbuild makes a new prerelease.

Step 0 of this cloudbuild succeeds, and the extension is updated.

Then the cloudbuild "fails" 

<img width="412" alt="Screen Shot 2022-09-29 at 12 55 22 PM" src="https://user-images.githubusercontent.com/66150587/193129505-116ae97b-ca3d-4af0-89e9-659eb3ffc0dd.png">

Which means every commit to main has a red X next to it, as if it were a bad commit.

We should fix this.

I wasted a couple of hours on it, and am now moving on.

**Comment by whscullin** [comment]
Fixed with https://github.com/malloydata/malloy-vscode-extension/pull/7
