### ISSUE TITLE
Removing a sort by field from a default query doesn't update the query

### ISSUE THREAD

**Issue by vitorleepkaln** [looker-open-source/malloy#883]
I noticed that when opening the `by_title` query from the homepage, I see a query with 3 selected fields,  and a sort by field. 

When I remove any of the selected fields from the query, the Malloy tab never changes the `order_by: 3 desc` statement, resulting in `Cannot destructure property 'queryResult' of 'undefined' as it is undefined.`

![2022-10-25_15-34-52 (1)](https://user-images.githubusercontent.com/48486336/197803169-509cfbac-b080-4947-b821-75853d13c42f.gif)

Clearing the query and starting from scratch, it seems to be specific to the prebuilt queries. However, with  new queries, the Malloy tab is updated with the field name rather than its index.

**Comment by lloydtabb** [comment]
@christopherswenson it looks like you aren't removing the order by when the field is removed from a query.
