### ISSUE TITLE
Make composer work with a config file for which sources, readmes, etc to load

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#886]
Right now, we show ALL of the `.malloy` files and all of the sources in them in the "Select analysis..." menu. This is needlessly messy--in many cases for a given dataset you will only want to surface one or a couple sources and with the others appearing only as they join in.  

Take this example:
<img width="379" alt="Screen Shot 2022-10-25 at 3 44 34 PM" src="https://user-images.githubusercontent.com/7178946/197906505-7d5ccc33-40be-4bca-bfa0-cee966715145.png">

Two of the files just have a bunch of queries and there's no source to even view inside of them. Those files are perfectly valid malloy code and are as they need to be for the fiddle, but it hurts the clean reusability of malloy models. Really the only source I want to surface from imdb is movies2. 

After chatting with @lloydtabb , one solution he proposed was some sort of json or other config file that specifies which source(s) and file(s) to look at for the composer.

**Comment by christopherswenson** [comment]
After a discussion with @lloydtabb an initial design for this could look like the following.

`composer_config.json`:
```
{
  "datasets": [
    {
      "title": "IMDB",
      "path": "/path/to/imdb/directory",
      "icon": "./path/to/icon.svg", // or png or jpeg
      "description": "This is a cool dataset!",
      "readme": "./path/to/readme.md", // if unspecified, looks for "./readme.json" (case insensitive)
      "includeModels": [ // if unspecified, all model files in the directory are included
        {
          "path": "./path/to/model.malloy",
          "includeSources": ["foo", "bar", "baz"] // if unspecified, all sources are included
        },
        ...
      ]
    },
    ...
  ],
}
```

These "datasets" would then appear in the Composer in a new sidebar tab "Datasets" (assuming there were more than one).

Sidebar tabs would be reordered: Datasets, About, Query.

"About" sidebar tab is renamed to something else. (Not sure what: index? readme?)

If there is more than one dataset, app opens to the "Datasets" tab. If there is exactly one, it is opened and the app opens to its "About" tab. If there is no readme file, then it just opens to a query.

**Comment by christopherswenson** [comment]
Old design from @tschomer for showing "Samples". This would likely be pretty similar.
![image (32)](https://user-images.githubusercontent.com/3538955/198082344-d73bc15a-7faf-4caa-b27d-a716eb199fe2.png)

**Comment by anikaks** [comment]
Nice, that sounds like a great solution.

I can't believe I'm going to ask this, but do we want to consider YAML/TOML/anything else for the config? I detest writing JSON by hand, even more than I detest troubleshooting YAML parse errors. Looking at that above example and thinking about hand-writing it made me feel sad.

**Comment by christopherswenson** [comment]
I would be okay with something else. TOML is nice. Personally YAML makes me sad. 

Pro for TOML:
- TOML is way easier to write than JSON
- TOML has comments, JSON has none

Pro for JSON:
- JSON is more well-known
- JSON parsing is easier than TOML and available out of the box in JS

**Comment by anikaks** [comment]
YAML also makes me sad (slightly less sad than writing JSON by hand though), TOML looks like a solid option!
