### ISSUE TITLE
Import inheritance issue when using `from()`

### ISSUE THREAD

**Issue by anikaks** [looker-open-source/malloy#911]
Something strange is happening with imports, where they are not fully being inherited as expected when `from()` is used. I can zip up the files for easy repro but will summarize here.

I have a source defined in a file, `mp_order_items.malloy`:
```
source: order_items is table('malloy-data.ecomm.order_items')
```

I then import this into a second file, `mp_middle.malloy` where I introduce an additional source, `users` and define a query on top of `order_items`:
```
import "mp_order_items.malloy"

source: users is table('malloy-data.ecomm.users'){
  primary_key: id
}

source: test is from(order_items -> {project: *})
```

Finally, in a third file `mp_ext.malloy` I import `mp_middle.malloy` and run a query against the `users` source:
```
// import "mp_order_items.malloy"
import "mp_middle.malloy"

query: test_middle is users -> {
  group_by: id
}
```

This `test_middle` query will fail, with error `Struct order_items not found in model.`

If I uncomment `import "mp_order_items.malloy"` it works as expected.
If I don't use `from` in the middle file, for example just defining a source or query against `order_items`, everything works as expected even without the extra import.

Reported by @doit-mattporter

**Comment by anikaks** [comment]
[mp_import_bug_repro.zip](https://github.com/looker-open-source/malloy/files/9931802/mp_import_bug_repro.zip)
 let me know if that zip doesn't work.

**Comment by mtoy-googly-moogly** [comment]
OK, the actual bug is that the bare import statement only imports sources not queries.
I think that's just wrong, and should be fixed, I'll wave it in front of people first just to make sure.
It should import sources and queries, but not SQL blocks, I believe.

**Comment by mtoy-googly-moogly** [comment]
nope i'm wrong about that ... i'm on it, more when i actually know things

**Comment by mtoy-googly-moogly** [comment]
Well this is super confusing ... why, when running "test_middle" does it even care about "order_items"

**Comment by mtoy-googly-moogly** [comment]
I know more things now.

1) I still don't know why, when parsing `mp_ext` the query in `mp_middle` is being loaded. That still seems weird and possibly broken, but maybe it isn't.

2) I understand why the load is failing. Imported things are not exported. Imported things are private. However we don't do the right thing when references to a private source or query are imported.
